version: '3.3'

volumes:
  store_data:
  db_data:
  rabbitmq_data:

services:
  app:
    image: mytardis/k8s-mytardis-prod:latest
    ports:
      - 8000:8000
    volumes:
      - store_data:/var/store
      - ./docker/app.settings.py:/app/tardis/settings.py
    env_file:
      - ./docker/app.env
    depends_on:
      - db
      - rabbitmq
  celery:
    image: mytardis/k8s-mytardis-prod:latest
    command: celery -A tardis.celery.tardis_app worker --queues=celery --loglevel=debug
    environment:
      - DJANGO_SETTINGS_MODULE=tardis.settings
    volumes:
      - store_data:/var/store
      - ./docker/app.settings.py:/app/tardis/settings.py
    env_file:
      - ./docker/app.env
    depends_on:
      - db
      - rabbitmq
  filters:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tardis.celery.app worker --queues=filters --loglevel=debug
    environment:
      - DJANGO_SETTINGS_MODULE=tardis.settings
    volumes:
      - ./:/app
      - store_data:/var/store
    env_file:
      - ./docker/app.env
    depends_on:
      - db
      - rabbitmq
      - memcached
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./docker/db.env
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    volumes:
      - rabbitmq_data:/data
    env_file:
      - ./docker/rabbitmq.env
  memcached:
    image: memcached:1.5.12
    ports:
      - 11211:11211
